@baseUrl = http://localhost:8000

### Register Admin
POST {{baseUrl}}/api/admin/signup
Content-Type: application/json

{
  "inviteCode": "supersecret",
  "username": "admin",
  "email": "admin@example.com",
  "password": "password123"
}

### Login Admin
# @name login
POST {{baseUrl}}/api/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password123"
}

### Access Protected Route with extracted token
GET {{baseUrl}}/api/event
Authorization: Bearer {{login.response.body.token}}

### Invalid Token Example
GET {{baseUrl}}/api/event
Authorization: Bearer invalid_token
