### Create Event
POST http://localhost:8000/api/event HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Sample Event",
  "description": "This is a sample event for testing.",
  "date": "2025-05-01",
  "image_url": "https://example.com/sample-event.jpg"
}

### Get All Events
GET http://localhost:8000/api/event HTTP/1.1

### Get Event by ID (Replace {id} with actual event ID after creating it)
GET http://localhost:8000/api/event/1 HTTP/1.1

### Update Event (Replace {id} with actual event ID)
PUT http://localhost:8000/api/event/1 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Updated Sample Event",
  "description": "This is an updated description for the event.",
  "date": "2025-06-01",
  "image_url": "https://example.com/updated-event.jpg"
}

### Delete Event (Replace {id} with actual event ID)
DELETE http://localhost:8000/api/event/15 HTTP/1.1
Authorization: Bearer {{token}}

