@baseUrl = http://localhost:8000

### Create Event
POST {{baseUrl}}/api/event
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "title": "Sample Event",
  "description": "This is a sample event for testing.",
  "date": "2025-05-01",
  "image_url": "https://example.com/sample-event.jpg"
}

### Get All Events
GET {{baseUrl}}/api/event

### Get Event by ID
GET {{baseUrl}}/api/event/1

### Update Event
PUT {{baseUrl}}/api/event/1
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "title": "Updated Sample Event",
  "description": "This is an updated description for the event.",
  "date": "2025-06-01",
  "image_url": "https://example.com/updated-event.jpg"
}

### Delete Event
DELETE {{baseUrl}}/api/event/1
Authorization: Bearer {{login.response.body.token}}
